name: Devtron-auto-labeller

on:
  issue_comment:
    types: [created]


jobs:
  manage-labels:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 3: Authenticate using GitHub CLI
      - name: Authenticate with GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GH_SYSTEMSDT_TOKEN }}

      # Step 4: Parse and manage labels
      - name: Parse and manage labels
        run: |
          set -e
          set -x  # Enable debugging

          # Extract the comment body and issue/PR number
          COMMENT_BODY=$(jq -r '.comment.body' "$GITHUB_EVENT_PATH")
          ISSUE_NUMBER=$(jq -r '.issue.number // .pull_request.number' "$GITHUB_EVENT_PATH")

          # Get the existing labels on the issue or PR
          EXISTING_LABELS=$(gh issue view "$ISSUE_NUMBER" --json labels -q '.labels[].name')

          # Add Label Logic
          if [[ "$COMMENT_BODY" =~ ^/([^ ]+)$ ]]; then
            LABEL_NAME="${COMMENT_BODY:1}"

            # Check if the label exists in the repository
            if gh label list --json name -q '.[].name' | grep -q "^$LABEL_NAME$"; then
              # Add the requested label, keeping existing ones intact
              gh issue edit "$ISSUE_NUMBER" --add-label "$LABEL_NAME"
              echo "Successfully added label '$LABEL_NAME' to issue/PR #$ISSUE_NUMBER."
            else
              echo "The label '$LABEL_NAME' doesn't exist in the repository. Please create it first."
            fi
          fi

          # Remove Label Logic
          if [[ "$COMMENT_BODY" =~ ^/remove[[:space:]](.+)$ ]]; then
            LABEL_NAME_TO_REMOVE=$(echo "$COMMENT_BODY" | sed -n 's|/remove ||p')

            # Remove the specified label
            if echo "$EXISTING_LABELS" | grep -q "^$LABEL_NAME_TO_REMOVE$"; then
              gh issue edit "$ISSUE_NUMBER" --remove-label "$LABEL_NAME_TO_REMOVE"
              echo "Successfully removed label '$LABEL_NAME_TO_REMOVE' from issue/PR #$ISSUE_NUMBER."
            else
              echo "The label '$LABEL_NAME_TO_REMOVE' is not attached to issue/PR #$ISSUE_NUMBER."
            fi
          fi
