name: Devtron-auto-labeller

on:
  issue_comment:
    types: [created]

jobs:
  manage-labels:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install gh cli
        uses: actions/setup-node@v3
        with:
          package: gh

      - name: Parse and manage labels
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Still needed for authentication with GitHub
        run: |
          #comment body and issue/PR number
          COMMENT_BODY=$(jq -r '.comment.body' "$GITHUB_EVENT_PATH")
          ISSUE_NUMBER=$(jq -r '.issue.number // .pull_request.number' "$GITHUB_EVENT_PATH")

          # Check for existing labels on issues and prs 
          EXISTING_LABELS=$(gh issue view $ISSUE_NUMBER --json labels | jq -r '.[].name')

          
          if [[ "$COMMENT_BODY" =~ ^/([^ ]+)$ ]]; then
            LABEL_NAME="${COMMENT_BODY:1}"

            # Existence of label in the repository
            if gh label list | grep -q "^$LABEL_NAME$"; then
              # Add the requested label, keeping existing ones intact
              UPDATED_LABELS=$(echo "$EXISTING_LABELS" | jq -R 'split("\n") | . + ["'"$LABEL_NAME"'"] | unique')
              gh issue edit $ISSUE_NUMBER --add-label "$LABEL_NAME"

              echo "Successfully added label '$LABEL_NAME' to issue/PR #$ISSUE_NUMBER."
            else
              echo "The label '$LABEL_NAME' doesn't exist in the repository. Please create it first."
            fi
          fi

          # Remove labels when asked
          if [[ "$COMMENT_BODY" =~ ^/remove[[:space:]](.+)$ ]]; then
            LABEL_NAME_TO_REMOVE=$(echo "$COMMENT_BODY" | sed -n 's|/remove ||p')

            # Remove the specified label 
            if echo "$EXISTING_LABELS" | grep -q "^$LABEL_NAME_TO_REMOVE$"; then
              gh issue remove-label $ISSUE_NUMBER --label "$LABEL_NAME_TO_REMOVE"

              echo "Successfully removed label '$LABEL_NAME_TO_REMOVE' from issue/PR #$ISSUE_NUMBER."
            else
              echo "The label '$LABEL_NAME_TO_REMOVE' is not attached to issue/PR #$ISSUE_NUMBER."
            fi
          fi
