name: Auto Label Issues

on:
  issue_comment:
    types: [created]

jobs:
  auto-label:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Parse and label issues
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Extract the comment body and the issue number
          COMMENT_BODY=$(jq -r '.comment.body' "$GITHUB_EVENT_PATH")
          ISSUE_NUMBER=$(jq -r '.issue.number' "$GITHUB_EVENT_PATH")

          # Check if the comment starts with a slash (/)
          if [[ "$COMMENT_BODY" =~ ^/ ]]; then
            # Remove the slash and use the rest as the label name
            LABEL_NAME="${COMMENT_BODY:1}"

            # Use GitHub API to check if the label exists
            LABELS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                      -H "Accept: application/vnd.github.v3+json" \
                      "https://api.github.com/repos/${{ github.repository }}/labels")

            if echo "$LABELS" | jq -e ".[] | select(.name == \"$LABEL_NAME\")" > /dev/null; then
              # Add the label to the issue
              curl -s -X POST -H "Authorization: token $GITHUB_TOKEN" \
                   -H "Accept: application/vnd.github.v3+json" \
                   -d "{\"labels\": [\"$LABEL_NAME\"]}" \
                   "https://api.github.com/repos/${{ github.repository }}/issues/$ISSUE_NUMBER"

              echo "Label '$LABEL_NAME' added to issue #$ISSUE_NUMBER."
            else
              echo "Label '$LABEL_NAME' does not exist in the repository."
            fi
          else
            echo "Comment does not start with '/'. No action taken."
          fi