name: Devtron-auto-labeller

on:
  issue_comment:
    types: [created]

jobs:
  manage-labels:
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Parse and manage labels
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          set -x  # Enable debugging

          # Extract comment body, issue number, and author
          COMMENT_BODY=$(jq -r '.comment.body' "$GITHUB_EVENT_PATH")
          ISSUE_NUMBER=$(jq -r '.issue.number // .pull_request.number' "$GITHUB_EVENT_PATH")
          COMMENT_AUTHOR=$(jq -r '.
